version: "3"
services:
  site:
    build: .
    restart: unless-stopped
    ports:
      - 8080:80
    healthcheck:
      test: wget -nv -t1 --spider http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
