name: Build and push docker image to registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push-to-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1
      - name: Prepare build number
        run: echo "::set-output name=registry_tag_id::${GITHUB_SHA:0:7}"
        shell: bash
        id: get_tag_id
        env:
          GITHUB_SHA: ${{ github.sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/bearologics/applandingpage:${{ steps.get_tag_id.outputs.registry_tag_id }}
